DROP TABLE IF EXISTS endpointhits CASCADE;

CREATE TABLE IF NOT EXISTS endpointhits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    ip varchar(255) NOT NULL,
    timestamp TIMESTAMP
);